### ISSUE TITLE
Base64.decode 'undefined', missing module.exports

### ISSUE THREAD

**Issue by flexxis** [dankogai/js-base64#42]
Hi,

when i require js-base64 via CommonJS

```
var js_base64_1 = require('js-base64');

js_base64_1.Base64.decode(output);
```

js_base64_1 will be not defined and i get an Base64.decode 'undefined' error.
But if i append an export declaration for the base64.js module

`module.exports.Base64 = global.Base64;`

in addition to 

```
global.Base64 = {
        VERSION: version,
      ...
        decode: decode,
};
```

the code runs fine. So my questions are:
1. Why does the code in its recent version not run in my environment / what am i doing wrong  / is it outdated?
2. What is the rationale for a 'global export of Base64' instead of a regular export? Can it be improved by a module.export?

**Comment by acwong00** [comment]
I have the same problem when using js-base64 with babel.

when I import it like this:

```javascript
import Base64 from 'js-base64'

Base64.encode('acwong')
```

will get `_jsBase2.default.encode is not a function` this error.

but when I use js-base64 like this:

```javascript
var Base64 = require('js-base64').Base64;
```

it runs fine

**Comment by dankogai** [comment]
Sould be fixed in https://github.com/dankogai/js-base64/commit/2bfbc30e8821350af562277f47610542fc568be3

**Comment by yamilelias** [comment]
Not fixed yet, needed to use it like @acwong00 said, not working if imported.
